---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: shoppie-app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "acdemoacr001.azurecr.io": {
          "username": "cicd-svc-user",
          "password": "geBdZ+qDaTjj4FqBqJwa8Gt/zNp5UJnnupaZPT/vZx+ACRBCsirW",
          "email": "chandraleka.ambi@presidio.com",
          "auth": "BASE64_ENCODED_USERNAME_COLON_PASSWORD"
        }
      }
    }