---
apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/chandra217/shoppie-app-deployment.git
  username: chandra217
  password: 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
