
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoppie-app.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ include "shoppie-app.fullname" . }}-backend
