apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shoppie-app.fullname" . }}-frontend
  labels:
    {{- include "shoppie-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "shoppie-app.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "shoppie-app.fullname" . }}-frontend
        {{- include "shoppie-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: BACKEND_URL
              value: "/api"
          ports:
            - containerPort: 8080
              name: http
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
