
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoppie-app.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "shoppie-app.fullname" . }}-frontend
